### PR TITLE
Update minor version of PHP to get latest security updates

### PR DESCRIPTION
**Pull request by aserv92**
For: Medology/arepa-general/issues/46

Update minor version of PHP to get latest security updates

### CODE REVIEW

**Comment by aserv92** [comment]
@fortoulrodolfo Not sure if anything uses this branch of this repo as CI is failing because it can not merge with master.

**Comment by aserv92** [comment]
> @fortoulrodolfo Not sure if anything uses this branch of this repo as CI is failing because it can not merge with master.
> 
> If we don't need this PR, lets close it.

Yes, HealthLabs.com uses `1.0`

**Review by izazueta — CHANGES_REQUESTED** [review]
I will suggest checking if heallthlabs can work with the master branch or merge master into 1.0

Screen Shot 2021-07-09 at 11 32 46 a m

**Comment by aserv92** [comment]
> I will suggest checking if heallthlabs can work with the master branch or merge master into 1.0
> 
> Screen Shot 2021-07-09 at 11 32 46 a m

@izazueta 

After digging a little further. It seems that this branch(1.0) is needed to be compatible with flexible mink 1.0 and is not supported by flexible mink 2.0. In order to update this library on HealthLabs to at least 2.1 we would need to upgrade HealthLabs to flexible-mink 2.0. Also it seems that merging this branch(1.0) with master would break compatibility for flexible mink 1.0.

**Review by izazueta — APPROVED** [review]

**Review by fortoulrodolfo — APPROVED** [review]
you have failing CI

**Pull request merged**
