### PR TITLE
Fix failing test (state value)

### PR DESCRIPTION
**Pull request by joshmedeski**
For https://github.com/Medology/healthlabs.com/issues/137

Test fails because it had the wrong value in the table

### CODE REVIEW

**Comment by joshmedeski** [comment]
!reassign testin @awesomeousPrime

**Comment by joshmedeski** [comment]
!reassign testing @awesomeousPrime

**Comment by medology-bugman** [comment]
Paging @awesomeousPrime to review the testing work in this pull request!

**Comment by awesomeousPrime** [comment]
@joshmedeski testing 👍 146191f

**Pull request merged**
